### ISSUE TITLE
Operation is not reversible

### ISSUE THREAD

**Issue by fletort** [plumdog/django_migration_testcase#30]
I got his error:

```Python
File "/usr/local/lib/python3.5/site-packages/django/db/migrations/executor.py", line 218, in unapply_migration
    state = migration.unapply(state, schema_editor)
  File "/usr/local/lib/python3.5/site-packages/django/db/migrations/migration.py", line 146, in unapply
    raise IrreversibleError("Operation %s in %s is not reversible" % (operation, self))
django.db.migrations.exceptions.IrreversibleError: Operation <RunPython <function move_Point at 0x7feb316df730>> in my_app.0008_move_message_point_to_device_location is not reversible
```

this move_point method is a personal migration method that move data.
May i need to make a reverse method of it ?

**Comment by fletort** [comment]
Ok i understant that we must define a reverse operation for this custom migration method added with runPython: https://docs.djangoproject.com/en/1.10/ref/migration-operations/#runpython

But... new question 😄  : how test this reverse code added ?
Can we apply a reverse migration in your test (for example before = "0002.." after = "0001...." ) ?
Is this really usefull ? As this reverse migration is never used with data ?

**Comment by clokep** [comment]
Personally I usually define a no-op / null (looks like Django now has a built in `RunSQL.noop`) for data migrations. Seems like it should be supported if it isn't too crazy though! 👍

**Comment by plumdog** [comment]
The migration needs to be reversible to be testable, because the test-case needs to be able to get to the state before it. It does this by migrating to that point, which requires it to migrate your migration backwards. If you don't care about the reverse operation, you can do:
```python
migrations.RunPython(fix_all_my_data, migrations.RunPython.noop)
```
The `before` and `after` options just need to be things that it can migrate to. So "before" just means "state to be at before we call `run_migration()`" and "after" just means "state to be at after we call `run_migration()`". There is (I think) no requirement that `before` is before `after`.

I would claim that it is useful to be able to test your reverse migrations. We might never want to run a reverse, but it may be the case that if a deployment goes wrong you will need to roll-back your database, and migrating my be preferable to loading a backup.

There is the possibility here of a problem where you specifically want a migration to be non-reversible, but you still want to test it running forwards. If that is relevant here, then ideas welcomed.

**Comment by fletort** [comment]
Yes, i am ok with you @plumdog .
Good things : i put in place tet for my migration and so realize that i need to develop reverse migration (you give me a good use case of the purpose of them) and so i need to develop test for them to 😄 .  All is ok .
But it's true that i did not realize before making my test that reverse migration need to be developed..... so finally it's a good thing to test the code !
